# The URL the site will be built for
base_url = "https://sail-montreal.github.io"

theme = "anpu"

# Optional: enable tags
taxonomies = [
    { name = "tags" },
    { name = "categories" },
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

[markdown.highlighting]
theme = "material-theme-ocean"

[extra]
# Put all your custom variables here
author = "SAIL Montreal"
logo_text = "SAIL Montreal"

enable_post_view_navigation = false
post_view_navigation_prompt = ""

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    
]

copyright_html = "<script src=\"/instantpage-5.1.0.js\" type=\"module\" defer></script>"

default_language = "en"
