# The URL the site will be built for
base_url = "https://sail-montreal.github.io"

title = "SAIL Montreal"
description = "Samsung AI Lab, Montréal"

theme = "pickles"

# Optional: enable tags
taxonomies = [
    { name = "tags" },
    { name = "categories" },
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "en"

[markdown.highlighting]
theme = "catppuccin-latte"

[extra]
# A line to display underneath the main title
subtitle = ""

# Text to display in the footer of the page (rendered as inline markdown)
copyright = "© SAIL Montreal"

# Your Google Analytics ID
analytics = ""

# KaTeX math formula support
katex_enable = false

# instant.page prefetching
instantpage_enable = true
