# The URL the site will be built for
base_url = "https://sail-montreal.github.io"

theme = "anpu"

# Optional: enable tags
taxonomies = [
    { name = "tags" },
    { name = "categories" },
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "SAIL Montreal"

[extra]
# Put all your custom variables here
author = "SAIL Montreal"
logo_text = "SAIL Montreal"

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    
]

copyright_html = "<script src=\"/instantpage-5.1.0.js\" type=\"module\" defer></script>"

default_language = "en"
